#default_language_version:
#  python: python3.11 # Keep in sync with pyproject.toml.

repos:
  - repo: https://github.com/alan-turing-institute/CleverCSV-pre-commit
    rev: v0.8.2      # or any later version
    hooks:
      - id: clevercsv-standardize