repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint-fix

  # - repo: https://github.com/jbzoo/csv-blueprint
  #   rev: 1.0.3
  #   hooks:
  #     - id: csv-blueprint
  #       args:
  #         - '--csv'
  #         - './tests/**/*.csv'
  #         - '--schema'
  #         - './tests/**/*.yml'
  #         - '--report'
  #         - 'table'
