name: Lint CSV Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
    lint:
        runs-on: "ubuntu-latest"
        timeout-minutes: 20
    
        steps:
          - name: "Checkout"
            uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            with:
              fetch-depth: 0

          - name: "csvlinter lint"
            uses: kcheriyath/csvlinter@V0.6.0
            with:
#              file_list: "space delimited list of files including path"
              find_pattern: "*.csv"
#              find_path: "./data"
              fail_on_error: "true"
#              extra_params: "--lazyquotes"              

          - name: "CSV Blueprint lint"
            uses: jbzoo/csv-blueprint@7ceffedc57436eb014760381abd55929e350d83b # 1.0.3
            with:
              csv: './*.csv'
              schema: './*.yml'
              skip-schema: 'yes'
          
