name: Lint CSV Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

permissions:
  contents: read
  statuses: write

jobs:
    lint:
        runs-on: "ubuntu-latest"
        timeout-minutes: 20
    
        steps:
          - name: "Checkout"
            uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            with:
              fetch-depth: 0

          - name: Run Super-Linter
            uses: github/super-linter@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2 # v7.3.0
            env:
              VALIDATE_CSV: true
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#          - name: "csvlinter lint"
#            uses: kcheriyath/csvlinter@776f3c1d25d37a339d3bcaea683efa1d0fee1576 # V0.6.0
