name: Lint CSV Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

permissions: {}

jobs:
    lint:
        runs-on: "ubuntu-latest"
        timeout-minutes: 20
        permissions:
          contents: write
          packages: read
          # To report GitHub Actions status checks
          statuses: write
    
        steps:
          - name: "Checkout"
            uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            with:
              fetch-depth: 0

          - name: Run Super-Linter
            uses: super-linter/super-linter/slim@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2 # v7.3.0
            env:
              ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              FIX_YAML_PRETTIER: true
              FIX_MARKDOWN_PRETTIER: true
              VALIDATE_NATURAL_LANGUAGE: false

          - name: Commit and push linting fixes
            # Run only on:
            # - Pull requests
            # - Not on the default branch
            if: >
              github.event_name == 'pull_request' &&
              github.ref_name != github.event.repository.default_branch
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
              branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
              commit_message: "chore: fix linting issues"
              commit_user_name: super-linter
              commit_user_email: super-linter@super-linter.dev
