name: Lint CSV Pull Request

on:
#  pull_request:
#    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  statuses: write

jobs:
  lint:
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    permissions:
      contents: write
      statuses: write
      packages: read

    steps:
      - name: "Checkout"
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: '0'
          token: ${{ secrets.WORKFLOW_PERMISSIONS_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.pull_request.head.ref }}
                    
      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2 # v7.3.0
        env:
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.pull_request.head.ref }}
          FIX_YAML_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_MARKDOWN_PRETTIER: true
#          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
#          MARKDOWN_LINTER_RULES: /github/workspace/.markdownlint.yaml
          YAML_CONFIG_FILE: .yaml-lint.yml
          VALIDATE_NATURAL_LANGUAGE: false
          IGNORE_GITIGNORED_FILES: true

#       - name: Commit and push linting fixes
#         if: always()
#         uses: stefanzweifel/git-auto-commit-action@v5.1.0
#         with:
#           branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
#           commit_message: "chore(super-linter): fix linters"
# #          commit_user_name: "github-actions[bot]"
#           commit_user_email: "super-linter@users.noreply.github.com"
#           commit_author: "Super Linter <super-linter@users.noreply.github.com>"

