name: Lint CSV Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

permissions: {}

jobs:
    lint:
        runs-on: "ubuntu-latest"
        timeout-minutes: 20
        permissions:
          contents: write
          packages: read
          statuses: write
    
        steps:
          - name: "Checkout"
            uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            with:
              fetch-depth: 0

          - name: Run Super-Linter
            uses: super-linter/super-linter/slim@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2 # v7.3.0
            env:
              ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              FIX_YAML_PRETTIER: true
              FIX_MARKDOWN_PRETTIER: true
              VALIDATE_NATURAL_LANGUAGE: false

          - name: Commit and push linting fixes
#            if: >
#              github.event_name == 'pull_request' &&
#              github.head_ref != github.event.repository.default_branch
            uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
            with:
              branch: ${{ github.head_ref }}
              commit_message: "chore(super-linter): fix linting issues"
              commit_user_name: super-linter
              commit_user_email: super-linter@super-linter.dev
              commit_author: "super-linter <super-linter@super-linter.dev>"
              repository: ${{ github.repository }}
              token: ${{ secrets.GITHUB_TOKEN }}
