name: Deploy to GitHub Pages

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  gh-pages:
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'github-pages' || 'preview-pages' }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install
          npm ci
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Python dependencies
        working-directory: ./src/tag-generator
        run: |
          python -m pip install --upgrade pip
          pip check || true  # Verificar conflictos
          pip install -r requirements.txt --no-deps
          pip install -r requirements.txt
      
      - name: Build static files
        working-directory: ./src/tag-generator
        run: |
          mkdir -p ../../dist
          cp -r static templates ../../dist/
          cp app.py ../../dist/
          cp ../../tags.yml ../../dist/  # Ahora el archivo existe en el directorio correcto
      
      - name: Generate artifact name
        id: artifact-name
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          SAFE_BRANCH_NAME="${BRANCH_NAME//\//-}"
          echo "name=pages-${SAFE_BRANCH_NAME:-main}" >> $GITHUB_OUTPUT
      
      - name: Build
        run: npm run build
        env:
          GITHUB_PAGES_BRANCH: ${{ github.ref_name }}
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: ${{ steps.artifact-name.outputs.name }}
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ steps.artifact-name.outputs.name }}
