name: Lint Pull Request

on:
  workflow_dispatch:
  #  pull_request:
  #    types: [ opened, reopened, synchronize, edited ]

permissions:
  contents: read
  statuses: write

jobs:
    lint:
        runs-on: "ubuntu-latest"
        timeout-minutes: 20
    
        steps:
          - name: "Checkout"
            uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            with:
              fetch-depth: 0
    
          - name: "Set up Python"
            uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
            with:
              python-version: "3.11"
    
          - name: "Cache pre-commit hooks"
            uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # 4.2.2
            with:
              path: ~/.cache/pre-commit
              key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
    
          - name: "Install the latest version of uv"
            uses: astral-sh/setup-uv@f3bcaebff5eace81a1c062af9f9011aae482ca9d # v3.1.7
            with:
              version: "latest"
              enable-cache: true
    
          - name: "Run pre-commit"
            run: uvx pre-commit run --all-files --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}